### ISSUE TITLE
Parser muenchen.py responds with an emtpy array

### ISSUE THREAD

**Issue by serupp** [mswart/openmensa-parsers#76] opened 2018-04-07 08:12 UTC
Hi,
thank you for this great project. We are using the parser for quite some time now (via openmensa.org) and it has always worked great, but since a couple of days we get an empty array as response instead of a list of meals. 
It seems that the website http://www.studentenwerk-muenchen.de/mensa has changed its layout and therefore the parsing does not work anymore. 
Do you have the time and are willing to adapt those changes so the API on openmensa.org works again?
Best regards

**Comment by klemens** [comment] 2018-04-07 14:12
The parser itself seems to work fine: http://omfeeds.devtation.de/muenchen/leopoldstrasse/today.xml

So it seems the feeds configured for `muenchen` on https://openmensa.org got messed up, eg. [leopoldstrasse](https://openmensa.org/c/133) was last fetched on 2018-03-11. I cannot the access the settings for `meunchen` to fix this, so I guess @mswart has to do it.

This also seems to be a more general problem, as my parsers (`leipzig` and `duesseldorf`) had the same problem some time ago that I fixed by removing the meta-urls for the canteens, which it seems have been put in by the index-url of the parser, although they don't work correctly, and manually re-adding the missing feeds.

I just quickly checked every parser and at least the following ones have not been updated since almost a month:
* `aachen`
* `dresden`
* `hamburg`
* `hannover`
* `karlsruhe`
* `magdeburg`
* `marburg`
* `ostniedersachsen`
* `wuerzburg`

`siegen` doesn't seem to have a parser configured?

**Comment by Harry-R** [comment] 2018-04-12 10:06
I can confirm the problem for Aachen. `Mensa Academica` works fine, but for example `Mensa Ahorn` is broken. The parser itself works for both mensas, but the Opensmensa Website and Android App don't show any information for `Mensa Ahorn`.

**Comment by Y0hy0h** [comment] 2018-04-12 10:24
I think that the parser side works fine. This issue should be escalated to [OpenMensa](https://github.com/openmensa/openmensa).

**Comment by klemens** [comment] 2018-04-20 14:58
This has been fixed (603be1568cf523fe55a423807696fd4423153ff5), so the affected canteens should start working again as of tomorrow.

**Comment by Y0hy0h** [comment] 2018-04-21 09:56
[Leopoldstraße](https://openmensa.org/c/133/2018-04-23) and [Templergraben](https://openmensa.org/c/94/2018-04-23) are showing the menues for next Monday. The previous week they both didn't show any entries.

Therefore the issue seems fixed and I'll close it. ;)

**Closed by Y0hy0h** 2018-04-21 09:56 UTC
